name: chromatic permalinks
on:
    pull_request:
        types: [opened]
        branches:
            - main
jobs:
    generate-links:
        name: generate links
        runs-on: ubuntu-latest
        steps:
            - name: Add PR comment
              uses: unsplash/comment-on-pr@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  msg: '### [Chromatic build](https://www.chromatic.com/builds?appId=601c6b2fcd385c002100f14c&branch=${{github.event.pull_request.head.ref}})'
                  check_for_duplicate_msg: true # OPTIONAL
